ALTER TABLE "Assessment" ALTER COLUMN "DateCreated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Assessment" ALTER COLUMN "DateUpdated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Assessment" ALTER COLUMN "DateDeleted" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Client" ALTER COLUMN "DateCreated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Client" ALTER COLUMN "DateUpdated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Client" ALTER COLUMN "DateDeleted" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "CurrentLivingSituation" ALTER COLUMN "InformationDate" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "CurrentLivingSituation" ALTER COLUMN "DateCreated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "CurrentLivingSituation" ALTER COLUMN "DateUpdated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "CurrentLivingSituation" ALTER COLUMN "DateDeleted" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "EmploymentEducation" ALTER COLUMN "InformationDate" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "EmploymentEducation" ALTER COLUMN "DateCreated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "EmploymentEducation" ALTER COLUMN "DateUpdated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "EmploymentEducation" ALTER COLUMN "DateDeleted" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Enrollment" ALTER COLUMN "EntryDate" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Enrollment" ALTER COLUMN "DateOfBCPStatus" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Enrollment" ALTER COLUMN "DateCreated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Enrollment" ALTER COLUMN "DateUpdated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Enrollment" ALTER COLUMN "DateDeleted" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Event" ALTER COLUMN "EventDate" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Event" ALTER COLUMN "ResultDate" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Event" ALTER COLUMN "DateCreated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Event" ALTER COLUMN "DateUpdated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Event" ALTER COLUMN "DateDeleted" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Exit" ALTER COLUMN "DateCreated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Exit" ALTER COLUMN "DateUpdated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Exit" ALTER COLUMN "DateDeleted" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Funder" ALTER COLUMN "DateCreated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Funder" ALTER COLUMN "DateUpdated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Funder" ALTER COLUMN "DateDeleted" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "HealthAndDV" ALTER COLUMN "DateCreated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "HealthAndDV" ALTER COLUMN "DateUpdated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "HealthAndDV" ALTER COLUMN "DateDeleted" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "HMISParticipation" ALTER COLUMN "DateCreated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "HMISParticipation" ALTER COLUMN "DateUpdated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "HMISParticipation" ALTER COLUMN "DateDeleted" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "IncomeBenefits" ALTER COLUMN "InformationDate" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "IncomeBenefits" ALTER COLUMN "DateCreated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "IncomeBenefits" ALTER COLUMN "DateUpdated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "IncomeBenefits" ALTER COLUMN "DateDeleted" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Inventory" ALTER COLUMN "DateCreated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Inventory" ALTER COLUMN "DateUpdated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Inventory" ALTER COLUMN "DateDeleted" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Organization" ALTER COLUMN "DateCreated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Organization" ALTER COLUMN "DateUpdated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Organization" ALTER COLUMN "DateDeleted" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Project" ALTER COLUMN "DateCreated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Project" ALTER COLUMN "DateUpdated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Project" ALTER COLUMN "DateDeleted" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "ProjectCoC" ALTER COLUMN "DateCreated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "ProjectCoC" ALTER COLUMN "DateUpdated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "ProjectCoC" ALTER COLUMN "DateDeleted" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Services" ALTER COLUMN "DateCreated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Services" ALTER COLUMN "DateUpdated" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "Services" ALTER COLUMN "DateDeleted" SET DATA TYPE text;